image: Visual Studio 2017

-
  branches:
    only:
      - master
  version: '{build}'
  init:
    - git config --global core.autocrlf true
  build_script:
  - ps: .\build.ps1 -Target Publish --BuildVersion=$($env:appveyor_build_version)
  artifacts:
  - path: BuildArtifacts\*.nupkg
  deploy:
    provider: NuGet
    api_key:
      secure: feaZhwWZx/Din7m6hadxDNQDT7Jv7Kcx4vLMXecUNIjNj7f3FAPLCBM6uY81C1ZS
    artifact: /.*\.nupkg/
    
# All branches
-
  version: '{build}'
  init:
    - git config --global core.autocrlf true
  build_script:
  - ps: .\build.ps1 -Target Test --BuildVersion=$($env:appveyor_build_version)
  artifacts:
  - path: BuildArtifacts\*.nupkg

  cache:
  - packages -> **\packages.config      
  - tools -> build.cake