# common configuration for ALL branches
image: Visual Studio 2017
version: '1.6.0.{build}'
init:
- git config --global core.autocrlf true
build_script:
- ps: .\build.ps1 -Target Test --BuildVersion=$($env:appveyor_build_version)
test: off
artifacts:
- path: BuildArtifacts\*.nupkg
cache:
- packages -> **\packages.config      
- tools -> build.cake

# here we are going to override common configuration
for:

# master branch
-
  branches:
    only:
      - master  
  build_script:
  - ps: .\build.ps1 -Target Publish --BuildVersion=$($env:appveyor_build_version) 
  deploy:
    provider: NuGet
    api_key:
      secure: feaZhwWZx/Din7m6hadxDNQDT7Jv7Kcx4vLMXecUNIjNj7f3FAPLCBM6uY81C1ZS
    artifact: BuildArtifacts\*.nupkg 